# Use the official R base image
FROM r-base:4.4.0

# Install necessary system dependencies
RUN apt-get update && apt-get install -y \
    libcurl4-openssl-dev \
    libssl-dev \
    libxml2-dev \
    libhdf5-dev \
    procps \
    pkg-config \
    texlive-full \
    pandoc \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# Install required R packages
RUN R -e 'install.packages(c("dplyr", "data.table", "ggplot2", "cowplot", "patchwork", "ggrepel", "tidyverse", "gridExtra", "ggbeeswarm", "rmarkdown", "tinytex"), repos="http://cran.rstudio.com/")'

# Set the working directory
WORKDIR /usr/local/src

# Set the default command to R
CMD ["R"]